- name: Add key for CMake Kitware repository
  ansible.builtin.apt_key:
    url: "{{ cmake_gpg_key_url }}"
    state: present

- name: Add CMake repository into sources.list.d/apt_kitware_com_ubuntu.list
  ansible.builtin.apt_repository:
    repo: '{{ cmake_deb_source }}'
    state: present
    update_cache: yes

- name: cmake dependencies
  ansible.builtin.apt:
    name:
      - "gpgv"
      - "gnupg"
    state: present
    update_cache: yes
    cache_valid_time: 3600

- name: apt install cmake
  ansible.builtin.apt:
    name: "cmake={{ cmake_version }}"
    state: present
  when: apt_kitware_com_retains_old_version
